/**
 * Changelog - Diario de novedades.
 * Siempre lo mas nuevo arriba.
 */
const Changelog = [
    {
        date: '03/05/2026 (sesion 8)',
        items: [
            { type: 'new', text: 'Importador de Captacion de socios activado. CSV de Looker (pestaña "New Store Membership", ES + IC). Cada fila = un socio captado por staff/tienda en una fecha. Member Id y Operating Company se descartan al importar para anonimizacion: la herramienta solo guarda que ese dia ese staff capto un socio' },
            { type: 'new', text: 'Importador de captacion: politica de reemplazo por rango. Cada importacion borra los socios previos cuyas fechas caen dentro del CSV nuevo y los sustituye. Re-importar no duplica filas' },
            { type: 'new', text: 'KPI "Socios" en Vista general (selector de columnas), Vista tienda/empleado (modo individual y compare) y barra de cobertura del Home. La columna placeholder "Socios" en Vista general deja de ser placeholder' },
            { type: 'new', text: 'Reconciliacion automatica de nombres de tienda en captacion contra Baby Banking. Cascada: quita prefijo "CeX ", ignora tildes, mayusculas y espacios. Para discrepancias mayores (palabras distintas, erratas) hay un set de aliases manuales precargado en data/captacion-store-aliases.json' },
            { type: 'new', text: 'Configuracion: editor de aliases de tienda colapsable con aviso "configuracion profunda" y mailto al desarrollador (abeatrice@webuy.com). Permite anadir, sobrescribir o restaurar aliases. Cualquier cambio reaplica al instante el reconciler a las filas ya importadas, sin re-importar' },
            { type: 'new', text: 'Drop zone placeholder para Attachment (% de ventas en tienda realizadas con socio). Mismo Looker que captacion, pestaña "Store Membership Attachment", ES + IC. Implementacion pendiente' },
            { type: 'change', text: 'Importador rediseñado: 6 drop zones cuadrados, compactos (150px) y centrados horizontalmente con grid auto-fit. Antes los cards eran rectangulos que ocupaban todo el ancho. Cards igualados en altura aunque algunos tengan solo una linea de descripcion' },
            { type: 'change', text: 'Barras de cobertura del Home reducidas en altura (~30%) para que las 6 fuentes quepan sin scroll en pantallas full HD' },
            { type: 'new', text: 'Popovers de info de drop-zones: detectan al hover si hay sitio arriba; si no, se abren hacia abajo. Antes podian quedar ocultos por la barra del navegador' },
            { type: 'new', text: 'Popovers escalan con scroll vertical interno cuando el contenido excede la altura disponible (max-height: calc(100vh - 80px))' },
            { type: 'fix', text: 'Popovers: las palabras en negrita ahora se ven. Cascada CSS .import-zone strong forzaba color oscuro sobre fondo oscuro del popover y las palabras destacadas quedaban invisibles' },
            { type: 'change', text: 'Popovers: z-index subido a 1000 y el card padre se eleva mediante :has() mientras el boton i esta activo, para que no queden por detras de cards adyacentes. Espaciado vertical uniformizado entre headings y texto' },
            { type: 'change', text: 'Vista detalle: filas con type="membership" se filtran al inicio del loop para no contaminar la lista de categorias (los socios no tienen categoria)' },
            { type: 'change', text: 'Data Explorer: filtro de tipo de transaccion incluye "Captacion de socios" (membership) para inspeccionar las filas importadas' },
        ]
    },
    {
        date: '23/04/2026 (sesion 7)',
        items: [
            { type: 'new', text: 'Vista tienda/empleado: modo comparar KPIs. Al fijar una sola tienda o empleado, la tabla cambia a filas=KPIs, columnas=semanas, con sparkline por fila. Multi-select de KPIs para elegir cuales comparar (6 por defecto)' },
            { type: 'new', text: 'Vista tienda/empleado: selector de empleado buscable (cuando scope=empleado) para entrar en modo comparar' },
            { type: 'fix', text: 'Vista tienda/empleado: el grafico de evolucion ya se muestra correctamente. Error silencioso (Y_AXIS_WIDTH indefinido) rompia el render de Chart.js y lo dejaba vacio' },
            { type: 'new', text: 'Vista tienda/empleado: cuando hay varios empleados/tiendas en el grafico, se muestra siempre una linea dasheada gris con el total agregado para dar contexto' },
            { type: 'fix', text: 'Vista tienda/empleado: tooltip del icono de info del grafico ya no se duplica (title nativo + custom al mismo tiempo) ni se corta con el borde del panel' },
            { type: 'new', text: 'Configuracion: filtro ecom por KPI. Cada KPI decide si incluye o excluye las ordenes de e-commerce. Se retira el switch "Filtrar ecom" de las 3 vistas. Por defecto: KPIs de volumen (Ventas, Refunds, Articulos) incluyen ecom; los de comportamiento presencial (Tickets, % Venta compl., % Gel/Mvl, etc.) lo excluyen' },
            { type: 'new', text: 'Vista general: filtro multi-select de tiendas (antes no tenia filtro propio de tiendas)' },
            { type: 'new', text: 'Vista general: grupos de tiendas guardables. Crea "Zona Norte", "Canarias", etc., aplicalos con un click. Se pueden renombrar, actualizar y eliminar. Compartidos con Vista detalle' },
            { type: 'new', text: 'Vista general: nuevas columnas % Venta compl., % Gel/Mvl, % Basics/Mvl. Se retiran los placeholders KPI 1-5. Socios y Stock se mantienen como placeholders' },
            { type: 'new', text: 'Vista general: selector de KPIs configurable. Eliges que columnas ver y en que orden (botones arriba/abajo). "Por defecto" resetea' },
            { type: 'change', text: 'Vista general: el TOTAL recalcula medias ponderadas correctas sobre el subconjunto visible de tiendas (no una suma ingenua)' },
            { type: 'new', text: 'Vista detalle: filtro por supercategoria. Mapping de 231 categorias a 7 supers (Juegos, Electronica, Informatica, Moviles, DVD, Accesorios Nuevos, Other), cargado desde data/categories-supercategories.json' },
            { type: 'new', text: 'Vista detalle: segmented control para elegir granularidad (Categoria o Supercategoria) - unicamente uno de los dos filtros esta activo a la vez' },
            { type: 'new', text: 'Vista detalle: boton swap para intercambiar ejes. Por defecto tiendas en filas y grupos en columnas; al pulsar, grupos en filas y tiendas en columnas. Util para comparar dos tiendas concretas' },
            { type: 'new', text: 'Vista detalle: boton de info (i) junto al filtro de categorias. Abre un popover con el mapa completo supercategoria -> categorias, con buscador. Solo lectura' },
            { type: 'new', text: 'Vista detalle: grupos de tiendas compartidos con Vista general. Los grupos que guardes en cualquiera de las dos vistas aparecen en ambas' },
            { type: 'change', text: 'Cabeceras de paneles: titulo + filtros ya no se estiran a los extremos. Ambos se agrupan centrados, alineados con la tabla centrada del body' },
            { type: 'change', text: 'Linea "Datos disponibles..." reubicada junto al titulo del modulo (section-header), fuera del area de trabajo. Quita ruido visual' },
            { type: 'new', text: 'Favicon (assets/favicon.png)' },
        ]
    },
    {
        date: '23/04/2026 (sesion 6)',
        items: [
            { type: 'new', text: 'Activado importador Baby Banking IC (Islas Canarias): parser reconoce headers IC (branchname, order_date, box_id, box_name, boxcategory)' },
            { type: 'change', text: 'Filtro de branches no-tienda (RMA, Ecomdistribution, Ecommerce) ahora es generico: captura variantes ES e IC' },
            { type: 'new', text: 'Drop zone de Baby Banking IC con link a Looker (dataset IC) e info sobre el proceso de importacion' },
            { type: 'new', text: 'Drop zone de Ecom Sales con link a Looker e info (incluye instruccion de filtrar region a ES+IC al exportar)' },
            { type: 'fix', text: 'Barra de cobertura de Ecom ahora muestra solo el rango efectivamente aplicado (interseccion con BB ES+IC). Los dias de Ecom sin BB que cruzar no cuentan como cobertura' },
            { type: 'new', text: 'Label "Datos disponibles" en los 3 dashboards: indica desde que W/año hasta cual hay datos cargados, con fechas de referencia' },
            { type: 'change', text: 'Auto-rellenado de rango de semanas: al abrir un dashboard por primera vez, los inputs se ajustan al rango de datos disponibles en lugar de 1-15 hardcoded' },
            { type: 'change', text: 'Vista detalle: selector de semana unica sustituido por rango (De W / a W). Suma metricas a lo largo del rango y muestra TOTAL por fila/columna. Tickets se contabilizan con Set de referencias unicas para evitar inflar totales cuando una orden abarca varias categorias' },
            { type: 'new', text: 'Vista detalle: filtros multi-select con checkbox para categorias y tiendas. Por defecto se muestran las 5 categorias top de la metrica activa; si cambias de metrica y no has tocado el filtro, se recalcula el top 5. Boton "Top 5 por metrica" para resetear la seleccion' },
            { type: 'new', text: 'Vistas general y detalle: click en cabecera de columna para ordenar. Primer click descendente, clicks sucesivos alternan' },
            { type: 'change', text: 'Vista general: filtro "Filtrar ecom" desactivado por defecto (antes venia activado)' },
            { type: 'fix', text: 'Performance: cache en memoria de la tabla de operaciones. Antes cada click de filtro/sort/cambio de metrica releia TODA la BD. Ahora solo se lee al arrancar o tras un import/restore/reset. Mejora drastica en interacciones (~10-20x mas rapido)' },
        ]
    },
    {
        date: '22/04/2026 (sesion 5 - parte 2)',
        items: [
            { type: 'change', text: 'Nombre de la app: KPI Tool 2026 -> CapiMetrics 2026 (topbar, titulo, backups). BD interna conserva el nombre anterior por compatibilidad' },
            { type: 'change', text: 'Home: saludo "Buenos dias" retirado, sustituido por logo de CapiMetrics (assets/logo.png)' },
            { type: 'change', text: 'Home armonizado con CapiTool: cards mas pequeñas (~15%) y con mismo formato horizontal en todas las secciones' },
            { type: 'change', text: 'Layout del home: Vistas arriba centradas, Cobertura + Data en 2 columnas debajo' },
            { type: 'change', text: '"Herramientas" renombrado a "Data"' },
            { type: 'change', text: 'Iconos de Data con colores: Configuracion ambar, Exportar violeta, Importar backup rosa, Google Drive verde' },
            { type: 'change', text: 'Contador de tiendas movido del saludo al label de Cobertura ("COBERTURA · N tiendas")' },
            { type: 'change', text: 'Distancia logo -> primera fila de cards reducida un 20%' },
            { type: 'new', text: 'Drop zone "Baby Banking IC" para Islas Canarias (inactiva hasta resolver diferencias de formato con ES)' },
            { type: 'new', text: 'Drop zone "Stocks (AIO)" para inventario desde AIO (inactiva, pendiente formato)' },
            { type: 'change', text: 'Cobertura muestra todas las fuentes (BB ES, BB IC, Ecom, Captacion, Stocks); las vacias aparecen con "sin datos"' },
            { type: 'change', text: 'Cross-reference de Ecom preparado para cruzar contra ES + IC cuando IC se active' },
            { type: 'change', text: 'Drop zone Attachment eliminada del importador' },
        ]
    },
    {
        date: '22/04/2026 (sesion 5)',
        items: [
            { type: 'new', text: 'Dashboard semanal: 3 vistas desde el home (General, Detalle, Tienda/empleado)' },
            { type: 'new', text: 'Vista general (Tiendas x KPIs): rango de semanas, suma de ventas netas, compras y % vale' },
            { type: 'new', text: 'Vista detalle (Tiendas x Categoria): desglose por categoria segun metrica' },
            { type: 'new', text: 'Vista tienda/empleado: unifica los antiguos paneles Ventas y Moviles en un solo panel con selector de KPI' },
            { type: 'new', text: 'Selector de KPI agrupado por familia (Ventas, Moviles, Compras) - preparado para ir añadiendo mas' },
            { type: 'new', text: 'Calculo de ventas netas: brutas menos refunds' },
            { type: 'new', text: 'Calculo de compras: cash buy + exchange, con % pagado en vale de tienda' },
            { type: 'new', text: 'Home reorganizado: solo 3 cards de vistas arriba, herramientas a la derecha (Importar CSV incluido)' },
            { type: 'change', text: 'Eliminadas secciones independientes de Ventas y Moviles. Su funcionalidad vive en Vista tienda/empleado' },
            { type: 'change', text: 'Importador: los refunds pasan a guardarse (antes se descartaban). Reimporta los CSV para disponer de ellos' },
            { type: 'change', text: 'Columnas pendientes (Socios, Stock, KPI 1-5) quedan como placeholders hasta definir origen' },
        ]
    },
    {
        date: '09/04/2026 (sesion 4)',
        items: [
            { type: 'new', text: 'KPI Ventas: tickets, articulos, facturacion, ventas multiples, % venta complementaria, media articulos/ticket' },
            { type: 'new', text: 'Home rediseñado: cards verticales 3:4 con icono, nombre y listado de metricas' },
            { type: 'new', text: 'Cobertura de datos en Home: barras por fuente (Baby Banking, Ecom) con fechas' },
            { type: 'new', text: 'Columna Tienda en tablas de evolucion con indicador de empleados multi-tienda (*)' },
            { type: 'new', text: 'Switch Unificar: fusiona apariciones del mismo empleado en varias tiendas' },
            { type: 'new', text: 'Columna de ranking (#) en todas las tablas de KPIs' },
            { type: 'new', text: 'Filtro minimo de operaciones para metricas porcentuales (configurable)' },
            { type: 'new', text: 'Heatmap gradual azul en celdas de metricas absolutas' },
            { type: 'new', text: 'Verificar datos: filtros por tienda, categoria, canal, fechas' },
            { type: 'new', text: 'Top 20 en selector de ranking' },
            { type: 'new', text: 'Scope "Por tienda" reemplaza "Total tienda" en evolucion' },
            { type: 'fix', text: 'Restablecer herramienta ahora borra la BD completamente (Dexie.delete)' },
            { type: 'fix', text: 'Importador filtra departamentos no-tienda (RMA, Ecomdistribution, Ecommerce)' },
            { type: 'fix', text: 'Totales de facturacion en Ventas calculados correctamente' },
            { type: 'fix', text: 'Filtrar ecom activado por defecto' },
            { type: 'new', text: 'Barra de progreso global al restaurar backups (overlay con porcentaje)' },
        ]
    },
    {
        date: '08/04/2026 (sesion 3)',
        items: [
            { type: 'new', text: 'Importador Ecom Sales activo: cruza ordenes ecom con Baby Banking y marca canal (ecom/tienda)' },
            { type: 'new', text: 'Campo "channel" en registros: distingue ventas en caja vs e-commerce' },
            { type: 'new', text: 'Switch "Solo tienda" en evolucion semanal: excluye ordenes ecom de los KPIs' },
            { type: 'new', text: 'Timeline de cobertura ecom con fechas de inicio/fin por tramo y huecos sin cobertura' },
            { type: 'new', text: '4 drop zones independientes en fila (Baby Banking, Ecom, Attachment, Captacion)' },
            { type: 'new', text: 'Hint contextual en cada drop zone (ej: "Datos globales, todas las tiendas")' },
            { type: 'new', text: 'Filas ecom sombreadas en violeta tenue en el explorador de datos (Verificar datos)' },
            { type: 'new', text: 'Columna Total sombreada en tabla de evolucion para diferenciarla de semanas' },
            { type: 'new', text: 'Escala del eje Y visible en el grafico, alineada en la columna previa' },
            { type: 'fix', text: 'Mapping Ecom Sales con fuzzy match: detecta headers con sufijos variables' },
            { type: 'fix', text: 'DB v5: index "source" en nueva version (Dexie no re-aplica schemas existentes)' },
            { type: 'fix', text: 'Init robusto: bindEvents siempre se ejecuta aunque falle la carga de settings' },
        ]
    },
    {
        date: '08/04/2026 (sesion 2)',
        items: [
            { type: 'new', text: 'Grafico de evolucion semanal con Chart.js: lineas por empleado o total tienda' },
            { type: 'new', text: 'Click en fila de la tabla para ver su grafico individual (+ total como referencia en linea discontinua)' },
            { type: 'new', text: 'Fila TOTAL tambien seleccionable para grafico' },
            { type: 'new', text: 'Selector Top N (Top 3, 5, 10, Todos) en filtros de evolucion: filtra tabla y grafico' },
            { type: 'new', text: 'Tooltip info (i) en el grafico explicando numerador/denominador de cada metrica' },
            { type: 'new', text: 'Panel unico de Moviles: eliminado resumen redundante, solo evolucion semanal con todos los filtros' },
            { type: 'new', text: 'Rango de semanas persistido en IndexedDB (se recuerda entre sesiones y en backups)' },
            { type: 'new', text: 'Explorador de datos movido dentro de Importar CSV como boton "Verificar datos" desplegable' },
            { type: 'new', text: 'Home: resumen muestra "Todo" por defecto al cargar' },
            { type: 'new', text: 'Boton "Novedades" en topbar con modal de changelog' },
            { type: 'fix', text: 'Chart.js: URL corregida a cdn.jsdelivr.net (version 4.4.4, la anterior daba 404)' },
            { type: 'fix', text: 'Error btn-drive-auth eliminado (rompia toda la inicializacion al estar sombreado Drive)' },
            { type: 'fix', text: 'Variable allStaff declarada antes de usarse en renderEvoChart (error de referencia)' },
        ]
    },
    {
        date: '08/04/2026 (sesion 1)',
        items: [
            { type: 'new', text: 'Estructura base del proyecto: HTML/CSS/JS, IndexedDB (Dexie.js), Papa Parse' },
            { type: 'new', text: 'Home profesional con sidebar, topbar, panel resumen con filtros de periodo y tienda' },
            { type: 'new', text: 'Importador CSV adaptado al formato Baby Banking ES de Looker (12 columnas)' },
            { type: 'new', text: 'Multi-source: botones para Baby Banking, Ecom Sales, Attachment, Captacion (3 ultimos proximamente)' },
            { type: 'new', text: 'Historial de importaciones con metadata: archivo, origen, fecha, rango de datos, tiendas, filas' },
            { type: 'new', text: 'Deduplicacion por fuente al importar (misma orden de distinta fuente NO es duplicado)' },
            { type: 'new', text: 'Optimizacion de almacenamiento: solo campos KPI-relevantes, descarte de transfers y refunds' },
            { type: 'new', text: 'Backup comprimido .json.gz (pako.js). Importacion soporta .gz y .json' },
            { type: 'new', text: 'Nombre de exports con fecha y hora: kpitool_export_2026-04-08_1109.json.gz' },
            { type: 'new', text: 'Restablecer herramienta con doble confirmacion y recomendacion de backup previo' },
            { type: 'new', text: 'Calendario de negocio: semanas sabado-viernes, semana 1 = 27/12/2025, configurable' },
            { type: 'new', text: 'KPI Moviles con porcentajes, desglose de unidades y colores (>40% verde, 30-40% amarillo, <30% rojo)' },
            { type: 'new', text: '% Combo: indicador de venta conjunta de geles + basics por movil' },
            { type: 'fix', text: 'Calculo de semanas con Date.UTC para evitar desfase por cambio de hora (DST)' },
            { type: 'fix', text: 'Fechas siempre en DD/MM/AAAA, input de texto en vez de date picker nativo' },
            { type: 'fix', text: 'Botones de confirmar/cancelar importacion visibles arriba sin necesidad de scroll' },
            { type: 'new', text: 'Google Drive sombreado como "proximamente"' },
        ]
    }
];
